language: node_js
sudo: false
node_js:
  - "6"
  - "8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
services:
  - redis
env:
  - TRAVIS=travis CC=gcc-4.9 CXX=g++-4.9
before_script:
  # LibCouchbase
  - sudo wget -O /etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1404.list
  - "sudo wget http://packages.couchbase.com/ubuntu/couchbase.key && sudo cat couchbase.key | sudo apt-key add -"
  - sudo apt-get update
  - sudo apt-get install libcouchbase2 libcouchbase-dev
  # Couchbase Server
  - sudo wget https://packages.couchbase.com/releases/4.5.1/couchbase-server-community_4.5.1-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_4.5.1-ubuntu14.04_amd64.deb
  - sudo service couchbase-server start
  # Init cluster
  - sleep 5
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=128
  # Setup buckets
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oose-hearbeat --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=16 --bucket-replica=0 -u Administrator -p password
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oose-inventory --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=16 --bucket-replica=0 -u Administrator -p password
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oose-job --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=16 --bucket-replica=0 -u Administrator -p password
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oose-peer --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=16 --bucket-replica=0 -u Administrator -p password
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=oose-purchase --bucket-password=password --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=16 --bucket-replica=0 -u Administrator -p password
