language: node_js
sudo: required
node_js:
  - "8"
services:
  - redis
env:
  - TRAVIS=travis
before_script:
  # LibCouchbase
  - sudo wget -O /etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1404.list
  - "sudo wget http://packages.couchbase.com/ubuntu/couchbase.key && sudo cat couchbase.key | sudo apt-key add -"
  - sudo apt-get update
  - sudo apt-get install libcouchbase2 libcouchbase-dev
  # Couchbase Server
  - sudo wget https://packages.couchbase.com/releases/4.5.1/couchbase-server-community_4.5.1-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_4.5.1-ubuntu14.04_amd64.deb
  - sudo service couchbase-server start
  # Init cluster
  - sleep 2
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=root --cluster-init-password=password --cluster-init-ramsize=1024 --cluster-index-ramsize=256 --cluster-fts-ramsize=256 --services=data,index,query,fts
  # Init couchbase
  - node bin/createCouchbaseBuckets.js root password
  - node bin/initCouchbase.js
  - node bin/createUser.js localhost bigpassword
