language: node_js
sudo: required
node_js:
  - "8"
services:
  - redis
env:
  - TRAVIS=travis
before_script:
  # LibCouchbase
  - sudo wget -O /etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1404.list
  - "sudo wget http://packages.couchbase.com/ubuntu/couchbase.key && sudo cat couchbase.key | sudo apt-key add -"
  - sudo apt-get update
  - sudo apt-get install libcouchbase2 libcouchbase-dev python-httplib2
  # Couchbase Server
  - sudo wget https://packages.couchbase.com/releases/5.0.0/couchbase-server-community_5.0.0-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_5.0.0-ubuntu14.04_amd64.deb
  - sudo service couchbase-server start
  # Init cluster
  - sleep 3
  - /opt/couchbase/bin/couchbase-cli cluster-init --cluster 127.0.0.1:8091 --cluster-username=root --cluster-password=password --cluster-ramsize=1024 --cluster-index-ramsize=256 --cluster-fts-ramsize=256 --cluster-name=localhost --index-storage-setting=default --services=data,index,query,fts
  # Init couchbase
  - DEBUG=stretchfs:couchbase node admin/bin/cbSetup.js
  - DEBUG=stretchfs:couchbase node admin/bin/userCreate.js localhost bigpassword
