language: node_js
sudo: false
node_js:
  - "7.4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - couchdb
  - redis
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - curl -X PUT http://localhost:5984/_config/admins/root -d '"blah1234"'
  - curl -X PUT http://root:blah1234@localhost:5984/oose
  - curl -X GET http://root:blah1234@localhost:5984/_config
  - >
    curl -X PUT http://root:blah1234@localhost:5984/_users/org.couchdb.user:oose
    -H "Accept: application/json"
    -H "Content-Type: application/json"
    -d '{"name": "oose", "password": "blah1234", "roles": [], "type": "user"}'
  - curl -X GET http://root:blah1234@localhost:5984/_users/org.couchdb.user:oose/
  - curl -X POST http://localhost:5984/_session -d 'name=oose&password=blah1234'